import streamlit as st
import torch
import os
from PIL import Image
from torchvision import transforms
import torch.nn.functional as F
from model import build_model, train_model
from data_loader import get_data_loaders

# Set up page configurations
st.set_page_config(page_title="AI Face Detector", layout="centered")
st.title("🛡️ Real vs Fake Face Detector")
st.write("Detect whether a human profile picture is Authentic or Generated by StyleGAN3 AI.")

# Constants
MODEL_PATH = "model_weights.pth"
CLASSES = ['fake', 'real'] # Maps to dataset subfolder alphabetical structure

@st.cache_resource
def load_or_train_model():
    """
    Loads pretrained model weights if they exist, 
    otherwise runs data download and a fast training epoch automatically.
    """
    model = build_model(num_classes=2)
    
    if os.path.exists(MODEL_PATH):
        # Load weights if already trained
        model.load_state_dict(torch.load(MODEL_PATH, map_location=torch.device('cpu')))
        model.eval()
        return model
    else:
        # Handles dataset setup and initial training silently under a single spinner
        with st.spinner("Downloading StyleGAN3 dataset and preparing model..."):
            # Trigger download and data loading
            train_loader, val_loader, class_names = get_data_loaders(batch_size=64)
            # Train for 1 fast epoch just to establish functionality
            model = train_model(model, train_loader, val_loader, epochs=1)
            model.eval()
            return model

# Initialize the model
try:
    model = load_or_train_model()
except Exception as e:
    st.error(f"Error initializing data/model: {e}")
    st.stop()

# Image Preprocessing for user uploads
def preprocess_image(image):
    transform = transforms.Compose([
        transforms.Resize((128, 128)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])
    # Add a batch dimension: [3, 128, 128] -> [1, 3, 128, 128]
    return transform(image).unsqueeze(0)

# Streamlit User Upload Interface
uploaded_file = st.file_uploader("Upload a face image (JPG, JPEG, PNG)...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    # Display the uploaded image
    image = Image.open(uploaded_file).convert("RGB")
    st.image(image, caption="Uploaded Face Image", use_container_width=True)
    
    st.write("🔬 *Analyzing image pixels for DeepFake fingerprints...*")
    
    # Process image & run prediction
    input_tensor = preprocess_image(image)
    
    with torch.no_grad():
        outputs = model(input_tensor)
        probabilities = F.softmax(outputs, dim=1)
        confidence, predicted_class_idx = torch.max(probabilities, 1)
        
    prediction = CLASSES[predicted_class_idx.item()]
    confidence_percentage = confidence.item() * 100
    
    # Display Verdict UI
    st.markdown("---")
    if prediction == 'real':
        st.success(f"### Verdict: **REAL HUMAN**")
        st.info(f"Confidence Level: **{confidence_percentage:.2f}%**")
    else:
        st.error(f"### Verdict: **FAKE / AI-GENERATED (StyleGAN3)**")
        st.info(f"Confidence Level: **{confidence_percentage:.2f}%**")